const express=require('express'); const db=require('../db'); const {authenticateToken}=require('../middleware/auth'); const r=express.Router(); r.use(authenticateToken); const f=['name','type','manufacturer','withdrawal_period_days','cost_per_unit','stock_quantity','notes']; const build=(b,fs)=>{const keys=fs.filter(k=>b[k]!==undefined);return{keys,vals:keys.map(k=>b[k])}};
r.get('/logs',async(req,res)=>{try{const {rows}=await db.query('SELECT ml.*,a.tag animal_tag,m.name medication_name FROM medication_logs ml LEFT JOIN animals a ON a.id=ml.animal_id LEFT JOIN medications m ON m.id=ml.medication_id ORDER BY treatment_date DESC');res.json(rows)}catch(e){res.status(500).json({error:'Failed to load medication logs'})}});
r.post('/logs',async(req,res)=>{try{const {animal_id,medication_id,dosage_id,treatment_date,dosage_given,dosage_unit,reason}=req.body;if(!animal_id||!medication_id||!treatment_date)return res.status(400).json({error:'Animal, medication, and date are required'});const {rows}=await db.query('INSERT INTO medication_logs(animal_id,medication_id,dosage_id,treatment_date,dosage_given,dosage_unit,reason,administered_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[animal_id,medication_id,dosage_id,treatment_date,dosage_given,dosage_unit,reason,req.user.id]);res.status(201).json(rows[0])}catch(e){res.status(400).json({error:'Failed to record medication'})}});
r.get('/',async(req,res)=>{try{const {rows}=await db.query('SELECT * FROM medications ORDER BY name');res.json(rows)}catch(e){res.status(500).json({error:'Failed to load medications'})}});
r.post('/',async(req,res)=>{try{if(!req.body.name)return res.status(400).json({error:'Medication name is required'});const {keys,vals}=build(req.body,f);const {rows}=await db.query(`INSERT INTO medications(${keys.join(',')}) VALUES(${keys.map((_,i)=>`$${i+1}`).join(',')}) RETURNING *`,vals);res.status(201).json(rows[0])}catch(e){res.status(400).json({error:'Failed to create medication'})}});
r.put('/:id',async(req,res)=>{try{const {keys,vals}=build(req.body,f);if(!keys.length)return res.status(400).json({error:'No valid fields provided'});vals.push(req.params.id);const {rows}=await db.query(`UPDATE medications SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')},updated_at=NOW() WHERE id=$${vals.length} RETURNING *`,vals);if(!rows[0])return res.status(404).json({error:'Medication not found'});res.json(rows[0])}catch(e){res.status(400).json({error:'Failed to update medication'})}});
r.delete('/:id',async(req,res)=>{try{const {rowCount}=await db.query('DELETE FROM medications WHERE id=$1',[req.params.id]);if(!rowCount)return res.status(404).json({error:'Medication not found'});res.json({message:'Medication deleted'})}catch(e){res.status(400).json({error:'Failed to delete medication'})}});
r.get('/:id/dosages',async(req,res)=>{try{const {rows}=await db.query('SELECT * FROM medication_dosages WHERE medication_id=$1 ORDER BY species',[req.params.id]);res.json(rows)}catch(e){res.status(500).json({error:'Failed to load dosages'})}});
r.post('/:id/dosages',async(req,res)=>{try{const {species,dosage_amount,dosage_unit,frequency}=req.body;const {rows}=await db.query('INSERT INTO medication_dosages(medication_id,species,dosage_amount,dosage_unit,frequency) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.params.id,species,dosage_amount,dosage_unit,frequency]);res.status(201).json(rows[0])}catch(e){res.status(400).json({error:'Failed to create dosage'})}}); module.exports=r;
