const express=require('express'); const db=require('../db'); const {authenticateToken}=require('../middleware/auth'); const r=express.Router(); r.use(authenticateToken);
const fields=['tag','name','species','breed','sex','date_of_birth','acquisition_date','weight','pen','status','source','parent_id','notes'];
function build(body){const keys=fields.filter(k=>body[k]!==undefined); return {keys, vals:keys.map(k=>body[k])};}
r.get('/stats/summary',async(req,res)=>{try{const a=await db.query("SELECT species,COUNT(*)::int count FROM animals GROUP BY species"); const s=await db.query("SELECT status,COUNT(*)::int count FROM animals GROUP BY status"); res.json({bySpecies:a.rows,byStatus:s.rows});}catch(e){res.status(500).json({error:'Failed to load animal statistics'});}});
r.get('/',async(req,res)=>{try{let q='SELECT * FROM animals WHERE 1=1',p=[]; ['species','status','pen'].forEach(k=>{if(req.query[k]){p.push(req.query[k]); q+=` AND ${k}=$${p.length}`}}); q+=' ORDER BY created_at DESC,id DESC'; const {rows}=await db.query(q,p); res.json(rows);}catch(e){res.status(500).json({error:'Failed to load animals'});}});
r.get('/:id',async(req,res)=>{try{const a=await db.query('SELECT * FROM animals WHERE id=$1',[req.params.id]); if(!a.rows[0])return res.status(404).json({error:'Animal not found'}); const w=await db.query('SELECT * FROM weight_records WHERE animal_id=$1 ORDER BY weight_date DESC',[req.params.id]); const m=await db.query('SELECT ml.*,m.name medication_name FROM medication_logs ml LEFT JOIN medications m ON m.id=ml.medication_id WHERE animal_id=$1 ORDER BY treatment_date DESC',[req.params.id]); res.json({...a.rows[0],weight_records:w.rows,medication_logs:m.rows});}catch(e){res.status(500).json({error:'Failed to load animal'});}});
r.post('/',async(req,res)=>{try{if(!req.body.tag||!req.body.species)return res.status(400).json({error:'Tag and species are required'}); const {keys,vals}=build(req.body); const cols=keys.join(','); const ps=keys.map((_,i)=>`$${i+1}`).join(','); const {rows}=await db.query(`INSERT INTO animals (${cols}) VALUES (${ps}) RETURNING *`,vals); res.status(201).json(rows[0]);}catch(e){res.status(400).json({error:e.constraint==='animals_tag_key'?'Animal tag already exists':'Failed to create animal'});}});
r.put('/:id',async(req,res)=>{try{const {keys,vals}=build(req.body); if(!keys.length)return res.status(400).json({error:'No valid fields provided'}); vals.push(req.params.id); const set=keys.map((k,i)=>`${k}=$${i+1}`).join(','); const {rows}=await db.query(`UPDATE animals SET ${set},updated_at=NOW() WHERE id=$${vals.length} RETURNING *`,vals); if(!rows[0])return res.status(404).json({error:'Animal not found'}); res.json(rows[0]);}catch(e){res.status(400).json({error:'Failed to update animal'});}});
r.delete('/:id',async(req,res)=>{try{const {rowCount}=await db.query('DELETE FROM animals WHERE id=$1',[req.params.id]); if(!rowCount)return res.status(404).json({error:'Animal not found'}); res.json({message:'Animal deleted'});}catch(e){res.status(400).json({error:'Failed to delete animal'});}});
r.post('/:id/weight',async(req,res)=>{try{const {weight,weight_date,notes}=req.body; if(!weight)return res.status(400).json({error:'Weight is required'}); const {rows}=await db.query('INSERT INTO weight_records(animal_id,weight_date,weight,notes,recorded_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[req.params.id,weight_date||new Date(),weight,notes||null,req.user.id]); await db.query('UPDATE animals SET weight=$1,updated_at=NOW() WHERE id=$2',[weight,req.params.id]); res.status(201).json(rows[0]);}catch(e){res.status(400).json({error:'Failed to add weight record'});}});
module.exports=r;
